# Generated by Django 2.1.5 on 2020-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200422_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
